export const constants = Object.freeze({
  MESSAGE_BROKER_CONFIG: 'MESSAGE_BROKER_CONFIG',
  MESSAGE_BROKER_PROVIDER: 'MESSAGE_BROKER_PROVIDER',
  LISTERS_TOKEN: 'LISTERS_TOKEN',
});


export const constants_metadata = Object.freeze({
  TOPIC_LISTENER_OPTIONS_METADATA_KEY: 'TOPIC_LISTENER_OPTIONS_METADATA_KEY'
});
